load("@3rdparty//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

py_binary(
  name = "main",
  srcs = ["main.py"],
  deps = [
    "//3rdparty/python:flaks",
    "//3rdparty/python:pandas",
  ]
)